"""
Notification service for sending email alerts on agent events.
Supports: application submitted, scam detected, job match found, daily summary.
"""

from __future__ import annotations

import smtplib
from email.message import EmailMessage
from typing import Any

from src.linked_agent.utils.logger import get_logger

logger = get_logger(__name__)


def _should_notify(settings: Any, event: str) -> bool:
    """Check if notifications are enabled for a given event type."""
    app = settings.application
    if not app.email_notifications_enabled:
        return False
    event_map = {
        "application.created": app.notify_on_apply,
        "application.failed": app.notify_on_failure,
        "scam.detected": app.notify_on_scam,
        "match.found": app.notify_on_match,
    }
    return event_map.get(event, False)


def _get_recipient(settings: Any) -> str | None:
    sender = settings.linkedin.gmail_otp_email
    app_password = settings.linkedin.gmail_app_password
    recipient = settings.application.email_recipient or sender
    if not sender or not app_password:
        return None
    return recipient


async def send_notification(
    settings: Any,
    event: str,
    subject: str,
    html_body: str,
) -> bool:
    """Send an email notification if enabled for the given event type."""
    if not _should_notify(settings, event):
        return False

    recipient = _get_recipient(settings)
    if not recipient:
        logger.debug(f"Notification not sent: no SMTP configured for event '{event}'")
        return False

    sender = settings.linkedin.gmail_otp_email
    app_password = settings.linkedin.gmail_app_password

    msg = EmailMessage()
    msg["Subject"] = f"[LinkedIn Agent] {subject}"
    msg["From"] = sender
    msg["To"] = recipient
    msg.set_content("Please enable HTML to view this email.")
    msg.add_alternative(html_body, subtype="html")

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(sender, app_password)
            smtp.send_message(msg)
        logger.info(f"Notification sent for event '{event}' to {recipient}")
        return True
    except Exception as e:
        logger.error(f"Failed to send notification for '{event}': {e}")
        return False


async def notify_application_submitted(
    settings: Any,
    job_title: str,
    company: str,
    match_score: float,
    applied_at: str,
) -> bool:
    subject = f"Applied to {job_title} @ {company}"
    html = f"""
    <html><body style="font-family:Arial;color:#333;">
    <h2 style="color:#2c3e50;">Application Submitted</h2>
    <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Role</b></td><td style="padding:8px;border:1px solid #ddd;">{job_title}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Company</b></td><td style="padding:8px;border:1px solid #ddd;">{company}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Match Score</b></td><td style="padding:8px;border:1px solid #ddd;">{match_score:.0f}%</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Applied At</b></td><td style="padding:8px;border:1px solid #ddd;">{applied_at}</td></tr>
    </table>
    <p style="margin-top:20px;font-size:12px;color:#777;">Generated by LinkedIn Agent</p>
    </body></html>
    """
    return await send_notification(settings, "application.created", subject, html)


async def notify_application_failed(
    settings: Any,
    job_title: str,
    company: str,
    error: str,
) -> bool:
    subject = f"Application Failed: {job_title} @ {company}"
    html = f"""
    <html><body style="font-family:Arial;color:#333;">
    <h2 style="color:#e74c3c;">Application Failed</h2>
    <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Role</b></td><td style="padding:8px;border:1px solid #ddd;">{job_title}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Company</b></td><td style="padding:8px;border:1px solid #ddd;">{company}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Error</b></td><td style="padding:8px;border:1px solid #ddd;color:red;">{error}</td></tr>
    </table>
    <p style="margin-top:20px;font-size:12px;color:#777;">Generated by LinkedIn Agent</p>
    </body></html>
    """
    return await send_notification(settings, "application.failed", subject, html)


async def notify_scam_detected(
    settings: Any,
    job_title: str,
    company: str,
    risk_score: float,
    reasons: list[str],
) -> bool:
    reasons_html = "<ul>" + "".join(f"<li>{r}</li>" for r in reasons) + "</ul>"
    subject = f"Scam Alert: {job_title} @ {company}"
    html = f"""
    <html><body style="font-family:Arial;color:#333;">
    <h2 style="color:#e74c3c;">Potential Scam Detected</h2>
    <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Role</b></td><td style="padding:8px;border:1px solid #ddd;">{job_title}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Company</b></td><td style="padding:8px;border:1px solid #ddd;">{company}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Risk Score</b></td><td style="padding:8px;border:1px solid #ddd;">{risk_score:.0f}%</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Reasons</b></td><td style="padding:8px;border:1px solid #ddd;">{reasons_html}</td></tr>
    </table>
    <p style="margin-top:20px;font-size:12px;color:#777;">Generated by LinkedIn Agent</p>
    </body></html>
    """
    return await send_notification(settings, "scam.detected", subject, html)


async def notify_match_found(
    settings: Any,
    job_title: str,
    company: str,
    match_score: float,
    url: str,
) -> bool:
    subject = f"High Match: {job_title} @ {company} ({match_score:.0f}%)"
    html = f"""
    <html><body style="font-family:Arial;color:#333;">
    <h2 style="color:#27ae60;">High Match Job Found</h2>
    <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Role</b></td><td style="padding:8px;border:1px solid #ddd;">{job_title}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Company</b></td><td style="padding:8px;border:1px solid #ddd;">{company}</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>Match Score</b></td><td style="padding:8px;border:1px solid #ddd;">{match_score:.0f}%</td></tr>
    <tr><td style="padding:8px;border:1px solid #ddd;"><b>URL</b></td><td style="padding:8px;border:1px solid #ddd;"><a href="{url}">{url}</a></td></tr>
    </table>
    <p style="margin-top:20px;font-size:12px;color:#777;">Generated by LinkedIn Agent</p>
    </body></html>
    """
    return await send_notification(settings, "match.found", subject, html)
