"""
Utility for sending email reports (e.g. external jobs list) via SMTP.
"""

import smtplib
from email.message import EmailMessage
from datetime import datetime
import typing

if typing.TYPE_CHECKING:
    from src.naukri_agent.config.settings import Settings
    from src.naukri_agent.models.entities import Job

from src.naukri_agent.utils.logger import get_logger

logger = get_logger(__name__)


def send_external_jobs_email(jobs_data: list[tuple["Job", str]], settings: "Settings") -> None:
    """
    Send an email containing a list of external jobs to apply to.

    Args:
        jobs_data: List of tuples containing (Job, external_url)
        settings: Application settings containing email configuration
    """
    if not jobs_data:
        logger.info("No external jobs to email.")
        return

    sender_email = settings.naukri.gmail_otp_email
    app_password = settings.naukri.gmail_app_password
    recipient = settings.application.email_recipient or sender_email

    if not sender_email or not app_password:
        logger.warning(
            "Cannot send external jobs email: gmail_otp_email or gmail_app_password is not configured."
        )
        return

    logger.info(f"Sending email report for {len(jobs_data)} external jobs to {recipient}...")

    msg = EmailMessage()
    msg["Subject"] = (
        f"Action Required: Naukri External Jobs ({datetime.now().strftime('%Y-%m-%d')})"
    )
    msg["From"] = sender_email
    msg["To"] = recipient

    # Create HTML content
    html_content = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #2c3e50;">Naukri Agent - External Jobs Report</h2>
        <p>The agent found <strong>{len(jobs_data)}</strong> jobs during the run that require you to apply directly on the company website.</p>
        <p>Please click the links below to apply to these roles:</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <thead>
            <tr style="background-color: #f8f9fa;">
              <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Role</th>
              <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Company</th>
              <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Location</th>
              <th style="padding: 12px; border: 1px solid #ddd; text-align: left;">Apply Link</th>
            </tr>
          </thead>
          <tbody>
    """

    for job, ext_url in jobs_data:
        # Fallback if external URL couldn't be extracted, use the Naukri URL
        apply_href = ext_url if ext_url else job.url
        apply_text = "Apply Here"

        title = job.title or "N/A"
        company = job.company or "N/A"
        location = job.location or "N/A"

        html_content += f"""
            <tr>
              <td style="padding: 12px; border: 1px solid #ddd;"><strong>{title}</strong></td>
              <td style="padding: 12px; border: 1px solid #ddd;">{company}</td>
              <td style="padding: 12px; border: 1px solid #ddd;">{location}</td>
              <td style="padding: 12px; border: 1px solid #ddd;">
                <a href="{apply_href}" style="display: inline-block; padding: 6px 12px; background-color: #007bff; color: white; text-decoration: none; border-radius: 4px;">{apply_text}</a>
              </td>
            </tr>
        """

    html_content += """
          </tbody>
        </table>
        <p style="margin-top: 30px; font-size: 12px; color: #777;">Generated by Naukri Agent</p>
      </body>
    </html>
    """

    msg.set_content("Please enable HTML to view this email.")
    msg.add_alternative(html_content, subtype="html")

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(sender_email, app_password)
            smtp.send_message(msg)
        logger.info(f"Successfully sent external jobs email to {recipient}")
    except Exception as e:
        logger.error(f"Failed to send email via SMTP: {e}")
